# Получить объявление по идентификатору
GET http://localhost:3000/offers/69c98315edbb02aef834bfd1 HTTP/1.1

###

## Получить список объявлений
GET http://localhost:3000/offers?limit=10 HTTP/1.1

###

## Удалить объявление по идентификатору

DELETE http://localhost:3000/offers/62825028a75295825778ac80 HTTP/1.1

###


## Список комментариев к объявлению
GET http://localhost:3000/offers/69c98315edbb02aef834bfd1/comments HTTP/1.1

###
