# Получить объявление по идентификатору
GET http://localhost:3000/offers/6a1475f5e8df7c0412530a85 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExMzY5MTQwMjUxZGFhZGFlZTVlMTM2IiwiaWF0IjoxNzc5NjU2OTg4LCJleHAiOjE3Nzk4Mjk3ODh9.x5fodXNwaoXr9sWf5MrWDOcqPw11srZt8cbTZlW8E8g

###

## Получить список объявлений
GET http://localhost:3000/offers?limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExMzY5MTQwMjUxZGFhZGFlZTVlMTM2IiwiaWF0IjoxNzc5NjkyODA2LCJleHAiOjE3Nzk4NjU2MDZ9.a5IhWu7p3c_7BAjrtENFqoSkRTBAlKlAlfS7jGiPAF4
###

## Создать новое объявление

POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExNDc1ZDVlOGRmN2MwNDEyNTMwYTgyIiwiaWF0IjoxNzc5NzI1Nzg3LCJleHAiOjE3Nzk4OTg1ODd9.hFl1pYW4ARmBGxkFB4JuxP48xWCg4GI80RUqDCbyX_w

{
  "title": "Modern apartment in city center",
  "description": "Beautiful and fully furnished place located in the heart of the city, perfect for travelers who want comfort and convenience.",
  "publishDate": "2026-02-15T00:00:00.000Z",
  "city": "Brussels",
  "previewImage": "https://example.com/images/brussels-preview.jpg",
  "images": [
    "https://example.com/images/brussels1.jpg",
    "https://example.com/images/brussels2.jpg",
    "https://example.com/images/brussels3.jpg",
    "https://example.com/images/brussels4.jpg",
    "https://example.com/images/brussels5.jpg",
    "https://example.com/images/brussels6.jpg"
  ],
  "isPremium": true,
  "type": "apartment",
  "rooms": 2,
  "guests": 3,
  "price": 1200,
  "facilities": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Baby seat",
    "Washer",
    "Towels",
    "Fridge"
  ],
  "location": {
    "latitude": 50.846557,
    "longitude": 4.351697
  }
}

###

## Удалить объявление по идентификатору
DELETE http://localhost:3000/offers/6a13635c0df9cd8bf6105552 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExMzY5MTQwMjUxZGFhZGFlZTVlMTM2IiwiaWF0IjoxNzc5NjU2OTg4LCJleHAiOjE3Nzk4Mjk3ODh9.x5fodXNwaoXr9sWf5MrWDOcqPw11srZt8cbTZlW8E8g

###

## Обновить объявление

PATCH http://localhost:3000/offers/6a1475f5e8df7c0412530a85 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExNDc1ZDVlOGRmN2MwNDEyNTMwYTgyIiwiaWF0IjoxNzc5NzI1Nzg3LCJleHAiOjE3Nzk4OTg1ODd9.hFl1pYW4ARmBGxkFB4JuxP48xWCg4GI80RUqDCbyX_w

{
  "isPremium": true,
  "price": 2800
}

###

## Список комментариев к объявлению
GET http://localhost:3000/offers/6a1475f5e8df7c0412530a85/comments HTTP/1.1

###

## Получить список премиальных объявлений по городу
GET http://localhost:3000/offers/premium?city=Paris&limit=10 HTTP/1.1

###

## Добавить в избранное

POST http://localhost:3000/offers/6a135a60cf8b052690407eae/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNmExMzY5MTQwMjUxZGFhZGFlZTVlMTM2IiwiaWF0IjoxNzc5NjkyMjAyLCJleHAiOjE3Nzk4NjUwMDJ9.4JQGX0uO4A8oYBLiE0i2y8jV_QCcR1fsVOVADKa1OP4

###

## Удалить из избранного

DELETE http://localhost:3000/offers/69c98315edbb02aef834bfd1/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNjllZTVmMzVmNjEzMTNjMWRkZjBkODJkIiwiaWF0IjoxNzc3ODk4MDMyLCJleHAiOjE3NzgwNzA4MzJ9.ZJqG9wZG5xLb3gyaJ3R5nWLgiVABfWiWbMpqd2-sILE

###

## Получить избранные объявления

GET http://localhost:3000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pY2hhZWwuYnJvd25AZXhhbXBsZS5jb20iLCJmaXJzdG5hbWUiOiJNaWNoYWVsIiwibGFzdG5hbWUiOiJCcm93biIsImlkIjoiNmExMzVhNjBjZjhiMDUyNjkwNDA3ZTlhIiwiaWF0IjoxNzc5NjkyNjY2LCJleHAiOjE3Nzk4NjU0NjZ9.4kJV6dKYs7NGEZsgTiO9W9e1cuV5YZcoUaf85S3PZ9c

###
